Integer timestamps support and filterColumns support
pratikkapasi/laravel-settings pull request #1
Opened 2017-10-13 22:36 UTC by pratikkapasi

- Adds 2 columns `created_at` and `updated_at` timestamps in the table. The epoch values of time is stored in the database, hence, integers.
- Currently, `setExtraColumns` function not only sets the extra columns, but also adds a filter for each of the column while looking up the table. This PR separates out the 2 operations, with the functions `setExtraColumns` which can be used only to set the extra columns, and `setFilterColumns` which can be used to apply filters for a particular field while looking up in the table.

2017-11-15 19:41 UTC, pratikkapasi commented
@amitmahbubani

2017-11-29 18:02 UTC, jitendra-1217 requested changes
As discussed offline:

- [ ] Need to decide if want to keep timestamps as int(some code changes) or timestmap(minimal code changes)
- [ ] Need to make sure application is able to set timezone (in either of above 2 approaches, whichever decided) by some method like setTimeZone() - usage that to get time() , the php method in first case, or sets db connection timezone to that in 2nd case.

The setting timezone would be optional feature. Will use php/ mysql's default, depends on what we do (1st todo ^).

2017-11-30 14:42 UTC, jitendra-1217 commented
Post discussion with sunny:

- We are going with this fork with int timestamp support.
- We are not worried about timezone thing as in api repo as well the same method gets used.

2017-12-01 18:32 UTC, jitendra-1217 approved these changes

2017-12-01 18:52 UTC, merged